<a href="https://colab.research.google.com/github/nefedov112/hello-world/blob/master/neironka.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import keras
from keras.models import Sequential
from keras.layers import Dense, Conv2D, MaxPooling2D, Dropout, Flatten
import matplotlib.pyplot as plt
import numpy as np
from os import listdir
from sklearn.model_selection import train_test_split

def loadImages(path):
  imagesList = listdir(path)
  loadedImages = []
  for image in imagesList:
    loadedImages.append(plt.imread(path + image))
  return np.array(loadedImages)

habitable = loadImages('./train2/habitable/') / 255
nohabitable = loadImages('./train2/nohabitable/') / 255

In [ ]:
photo = np.concatenate((habitable, nohabitable), axis=0)
label_first = np.concatenate((np.zeros(135), np.ones(135)), axis=0)
label_second = np.concatenate((np.ones(135), np.zeros(135)), axis=0)
label_almost = np.vstack((label_first, label_second))
label = label_almost.swapaxes(1,0)

In [3]:
X_train, X_test, y_train, y_test = train_test_split(photo, label, test_size = 0.1, random_state = 42)
model = Sequential()
model.add(Conv2D(32,kernel_size=(2,2), activation='relu'))
model.add(Conv2D(64,(3,3), activation='relu',))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(2, activation='softmax'))

In [4]:
model.compile(loss=keras.losses.binary_crossentropy,
              optimizer=keras.optimizers.Adam(),
              metrics=['accuracy'])

In [ ]:
model.fit(X_train, y_train,
          epochs=40,
          verbose=1,
          validation_data=(X_test, y_test))

In [20]:
imagesList = listdir('./test/')
test = []
test.append(plt.imread('./test/' + 'zavod58.jpg'))
test = np.array(test)
print(test.shape)
x_new_data = test / 255
print(x_new_data)
#prediction = model.predict(x_new_data)


(1, 1440, 1920, 3)
[[[[0.19215686 0.21176471 0.29019608]
   [0.16862745 0.18823529 0.26666667]
   [0.16862745 0.18823529 0.26666667]
   ...
   [0.03921569 0.03921569 0.03921569]
   [0.03921569 0.03921569 0.03921569]
   [0.03921569 0.03921569 0.03921569]]

  [[0.18823529 0.20784314 0.28627451]
   [0.17254902 0.19215686 0.27058824]
   [0.17254902 0.19215686 0.27058824]
   ...
   [0.04313725 0.04313725 0.04313725]
   [0.04705882 0.04705882 0.04705882]
   [0.04705882 0.04705882 0.04705882]]

  [[0.19215686 0.21176471 0.29019608]
   [0.17647059 0.19607843 0.2745098 ]
   [0.17647059 0.19607843 0.2745098 ]
   ...
   [0.04313725 0.04313725 0.04313725]
   [0.04705882 0.04705882 0.04705882]
   [0.05098039 0.05098039 0.05098039]]

  ...

  [[0.34117647 0.29803922 0.29019608]
   [0.33333333 0.29019608 0.28235294]
   [0.31764706 0.2745098  0.26666667]
   ...
   [0.15686275 0.16470588 0.07058824]
   [0.15686275 0.16470588 0.07843137]
   [0.16470588 0.17254902 0.08627451]]

  [[0.32941176 0.28627451 